spring:
  # REDIS数据库配置
  redis:
    # [可选] 超时时间
    timeout: 10000
    # 以下为单机配置
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: localhost
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 0
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: fastbee
    # 以下为集群配置
#        cluster:
#            nodes: 192.168.1.242:7001
#        password: 4767cb971b40a1300fa09b7f87b09d1c

# [可选] 监听的HTTP端口, 网页和接口调用都是这个端口
# 您需要使用实际的证书名称替换domain_name.jks
# 证书获取参考文档：https://help.aliyun.com/zh/ssl-certificate/user-guide/enable-https-on-spring-boot
server:
  port: 18081
  servlet:
    context-path: /         # 应用的访问路径
  #  HTTPS配置， 默认不开启
  ssl:
    # 是否开启HTTPS访问 默认关闭
    enabled: false
    # enabled: true
    # 证书文件路径，您需要使用实际的证书名称替换domain_name.jks。
    key-store: classpath:fastbee.online.jks
    # 证书密码 修改为对应密码
    key-store-password: fastbee
    # 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# [根据业务需求配置]
userSettings:
  # [必选 ] 服务ID
  id: 334533
  # [必选 ] zlm配置的录像路径
  record: D:\soft\ZLMediaKit\www\record
  # [可选 ] 录像保存时长（单位： 天）每天晚12点自动对过期文件执行清理
  recordDay: 7
  # [可选 ] 录像下载合成临时文件保存时长， 不配置默认取值recordDay（单位： 天）每天晚12点自动对过期文件执行清理
  # recordTempDay: 7
  # [必选 ] ffmpeg路径
  ffmpeg: D:\soft\ZLMediaKit\bin\ffmpeg
  # [必选 ] ffprobe路径， 一般安装ffmpeg就会自带， 一般跟ffmpeg在同一目录,用于查询文件的信息
  ffprobe: D:\soft\ZLMediaKit\bin\ffprobe
  # [可选 ] 限制 ffmpeg 合并文件使用的线程数，间接限制cpu使用率， 默认2 限制到50%
  threads: 2

# MyBatis配置
mybatis:
  typeAliasesPackage: com.sydh.oss.domain            # 搜索指定包别名
  mapperLocations: classpath*:mapper/**/*Mapper.xml     # 配置mapper的扫描，找到所有的mapper.xml映射文件
  configLocation: classpath:mybatis/mybatis-config.xml  # 加载全局的配置文件

swagger-ui:

# [可选] 日志配置, 一般不需要改
logging:
  file:
    name: logs/record.log
    max-history: 30
    max-size: 10MB
    total-size-cap: 300MB
  level:
    root: WARN
    com:
      fastbee:
        record: info
